// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrxvfwurdjzzuibuahju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyeHZmd3VyZGp6enVpYnVhaGp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTI5MTMsImV4cCI6MjA2OTI4ODkxM30.Ofmr-TfZfxV_AjikqlLmu6fYuO7zTKfDxmW_f3VGv-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});